version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    command: ["./entrypoint.sh"]
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    depends_on: 
       - db

  nginx:
    build: 
      context: nginx
    container_name: nginx
    command: ["./entrypoint.sh"] 
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
      - app
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
        - ./mysql/entrypoint:/docker-entrypoint-initdb.d
        - ./mysql/data:/var/lib/mysql
    environment: 
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
    networks: 
        - node-network

networks: 
  node-network:
    driver: bridge